services:
  - type: web
    name: hospital-mgmt-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_mgmt.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-mgmt-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hospital-mgmt-redis
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: hospital-mgmt-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://hospital-mgmt-api.onrender.com

databases:
  - name: hospital-mgmt-db
    plan: free
