services:
  - type: web
    name: hospital-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "1"
      - key: DJANGO_DEBUG
        value: "1"
      - key: PATIENT_SELF_SIGNUP_ENABLED
        value: "1"
